version: '3.1'
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: foodij
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
